site_name: HFT Notes
site_description: Открытый глоссарий по высокочастотной торговле
site_url: https://USERNAME.github.io/hft-notes/

repo_name: USERNAME/hft-notes
repo_url: https://github.com/USERNAME/hft-notes
edit_uri: edit/main/docs/

hooks:
  - hooks/section_index.py

theme:
  name: material
  language: ru

  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

plugins:
  - search:
      lang:
        - ru
        - en
  - awesome-nav

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables

  - pymdownx.details

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.inlinehilite
  - pymdownx.superfences

  - pymdownx.tasklist:
      custom_checkbox: true

  - toc:
      permalink: true
